version: 2
general:
  branches:
    only:
      - static-pages-third-times-the-charm

jobs:
  lint:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-python-3.7.0-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - run:
          name: Run linters
          command: make lint
      - save_cache:
          key: cache-python-3.7.0-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  test:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: cache-python-3.7.0-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - run:
          name: Run tests
          command: make test
      - save_cache:
          key: cache-python-3.7.0-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

workflows:
  version: 2
  build_lint_test:
    jobs:
      - lint
      - test
      # - deploy:
      #     requires:
      #       - linters
      #       - tests
